import type { Metadata } from "next";
import DocsLayout from "@/components/docs/DocsLayout";
import DocsContent from "@/components/docs/DocsContent";
import DocsImageBox from "@/components/docs/DocsImageBox";

export const metadata: Metadata = {
  title: "Two-Factor Authentication | Connetra Documentation",
  description: "Connetra documentation for Two-Factor Authentication.",
};

export default function TwoFactorAuthenticationPage() {
  return (
    <DocsLayout>
      <DocsContent
        title="Two-Factor Authentication"
        breadcrumbs={[
          { label: "Documentation", href: "/docs/intro" },
          { label: "Authentication & Access" },
          { label: "Two-Factor Authentication" }
        ]}
        prevPage={{ title: "Privacy & Security", href: "/docs/privacy-security" }}
        nextPage={{ title: "Single Sign-On", href: "/docs/authentication-access/single-sign-on" }}
      >
<p className="docs-lead-paragraph">
          Connetra provides an added layer of security by allowing Workspace Owners to mandate Two-Factor Authentication (2FA) for all members accessing the workspace. When enabled, users will be required to configure and verify an authentication code using an authenticator app (such as Google Authenticator) to gain access.
        </p>

        <h2 id="enabling-2fa" className="docs-article-h2">
          Enabling 2FA for a Workspace
        </h2>
        <p className="docs-article-p">
          Workspace Owners can enforce 2FA from the Workspace Settings. Once activated, any user attempting to access the workspace will be prompted to set up their Two-Factor Authentication.
        </p>

        <h2 id="setting-up-2fa" className="docs-article-h2">
          Setting Up 2FA
        </h2>
        <p className="docs-article-p">
          When you log in or switch to a workspace that requires 2FA for the first time, you will be guided through a setup process:
        </p>
        <ul className="docs-list">
          <li>A QR code and a secret key will be displayed on the screen.</li>
          <li>Scan the QR code using your preferred authenticator app (Google Authenticator, Authy, Microsoft Authenticator), or enter the secret key manually.</li>
          <li>Enter the 6-digit authentication code generated by your app to verify and complete the setup.</li>
        </ul>

        <h2 id="logging-in-with-2fa" className="docs-article-h2">
          Logging In with 2FA
        </h2>
        <p className="docs-article-p">
          Once you have configured 2FA, every subsequent login or access attempt to the secured workspace will require you to enter the 6-digit code from your authenticator app.
        </p>

        <h2 id="disabling-or-resetting-2fa" className="docs-article-h2">
          Disabling or Resetting 2FA
        </h2>
        <p className="docs-article-p">
          If a Workspace Owner disables the 2FA requirement for the workspace, members will no longer be prompted for a 2FA code.
        </p>
      </DocsContent>
    </DocsLayout>
  );
}
